### ISSUE TITLE
Version 1.0.0: User interface, codebase rebuild

### ISSUE THREAD

**Issue by electronfriends** [electronfriends/wemp#16]
I am motivated to make Wemp more than just a system tray menu. If we're going to use Electron, let's do it right.

Wemp will get a user interface, so I have migrated to `electron-vite` with Vue. The whole codebase will be rebuilt.

Since we previously had problems with Electron Forge (which were never solved), the switch to `electron-vite`, which uses Electron Builder, made even more sense.

If you want to see the progress on the next version, you can look at the [`dev`](https://github.com/electronfriends/wemp/tree/dev) branch.

## To-Do

- [ ] User interface
  - [x] List of services with buttons to start, restart, stop, etc.
  - [ ] Settings and switching between different paths.
  - [ ] Console showing actions or error messages in the current session. Like XAMPP.

- [ ] Service logic
  - [x] Download and extract the services.
  - [ ] Install the services and use the stubs to configure them.
  - [x] Start, restart and stop services.
  - [ ] Monitoring of changes to configuration files.

- [ ] New readme with screenshots of the user interface.

## Nice to have

- [ ] Download progress bar for each service.
- [ ] Get version of services automatically from its website. Probably needs to be hosted somewhere.
- [ ] Manual version setting for services. (kinda tricky because PHP's download file name often changes)
- [ ] Multiple language support.
- [ ] Maybe a new icon and logo for Wemp.

**Comment by OfficialAudite** [comment]
I recently started using WEMP. Awesome! Is it still ongoing project or you dont have time anymore ?

**Comment by electronfriends** [comment]
> I recently started using WEMP. Awesome! Is it still ongoing project or you dont have time anymore ?

Hey, glad you like it. I'm still working on it but the new version will take a while.

**Comment by OfficialAudite** [comment]
I'm a fullstack-backend dev. If you need some help with something I could help you. I've been using xampp and it is garbage :D +1 request, redis maybe

**Comment by electronfriends** [comment]
[Redis was already suggested](https://github.com/electronfriends/wemp/issues/7) but there was no official Windows support then, not sure how it is now. But I would like to keep Wemp minimal.

**Comment by OfficialAudite** [comment]
The original redis has no official windows support. But I think i was running: 

<details>
  <summary>Other project</summary>
  
https://github.com/zkteco-home/redis-windows
  
</details>

I understand the minimalistic approach. Maybe it would be possible then create something like addon ? aka you can create own config, something like service.redis.cfg and have required stuff like what to run where to find it etc. That would give possibility for people to add own stuff. For example I like running pocket base for some projects. But yeah thats just an idea

**Comment by electronfriends** [comment]
I've decided to stick with the tray menu for now, so I'm closing this.

New update will follow as soon as phpMyAdmin has fixed the problems with PHP 8.4.
